version: '3'

services:
        zookeeper:
                image: zookeeper:3.7.0
                container_name: zookeeper
                ports:
                        - "2181:2181"

        kafka:
                image: wurstmeister/kafka:2.12-2.5.0
                container_name: kafka
                ports:
                        - "9092:9092"
                environment:
                        DOCKER_API_VERSION: 1.22
                        KAFKA_ADVERTISED_HOST_NAME: localhost
                        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

        cmak:
                image: hlebalbau/kafka-manager:stable
                container_name: cmak
                ports:
                        - "8000:9000"
                environment:
                        ZK_HOSTS: "zookeeper:2181"
